language: python
sudo: false
python:
  - 2.7
install:
  - pip install -r requirements.txt
before_script:
  - flake8 . --exclude=".git,templates,migrations"
script:
  - py.test -v --ds=tastytaps.settings_test
